import type { NextPage } from 'next';
import Head from 'next/head';

import { useEffect } from 'react';

const Home: NextPage = () => {
	useEffect(() => {
		typeof document !== undefined
			? require('bootstrap/dist/js/bootstrap')
			: null;
	}, []);

	return (
		<>
			<Head>
				<title>Coffee Roaster</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<nav className='navbar navbar-expand-lg navbar-light bg-light'>
				<div className='container-fluid'>
					<a className='navbar-brand' href='#'>
						Navbar
					</a>
					<button
						className='navbar-toggler'
						type='button'
						data-bs-toggle='collapse'
						data-bs-target='#navbarNav'
						aria-controls='navbarNav'
						aria-expanded='false'
						aria-label='Toggle navigation'>
						<span className='navbar-toggler-icon'></span>
					</button>
					<div className='collapse navbar-collapse' id='navbarNav'>
						<ul className='navbar-nav'>
							<li className='nav-item'>
								<a className='nav-link active' aria-current='page' href='#'>
									Home
								</a>
							</li>
							<li className='nav-item'>
								<a className='nav-link' href='#'>
									Features
								</a>
							</li>
							<li className='nav-item'>
								<a className='nav-link' href='#'>
									Pricing
								</a>
							</li>
							<li className='nav-item'>
								<a className='nav-link disabled' href='#' aria-disabled='true'>
									Disabled
								</a>
							</li>
						</ul>
					</div>
				</div>
			</nav>
		</>
	);
};

export default Home;
